<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kenzhao.smallsteps</groupId>
    <artifactId>smallsteps-common-bom</artifactId>
    <version>0.0.1</version>
    <packaging>pom</packaging>

    <description>
        smallsteps-common-bom common依赖项
    </description>

    <dependencyManagement>
        <dependencies>
            <!-- 核心模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-core</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 接口模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-doc</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- excel -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-excel</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 幂等 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-idempotent</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 调度模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-job</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 日志记录 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-log</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 邮件服务 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-mail</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 数据库服务 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-mybatis</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- OSS -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-oss</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 限流 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-ratelimiter</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 缓存服务 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-redis</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- satoken -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-satoken</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 安全模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-security</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 短信模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-sms</artifactId>
                <version>0.0.1</version>
            </dependency>

            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-social</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- web服务 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-web</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 翻译模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-translation</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 脱敏模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-sensitive</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 序列化模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-json</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 数据库加解密模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-encrypt</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- 租户模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-tenant</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- WebSocket模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-websocket</artifactId>
                <version>0.0.1</version>
            </dependency>

            <!-- SSE模块 -->
            <dependency>
                <groupId>com.kenzhao.smallsteps</groupId>
                <artifactId>smallsteps-common-sse</artifactId>
                <version>0.0.1</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
