<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.kenzhao.smallsteps</groupId>
        <artifactId>smallsteps-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>smallsteps-child</artifactId>

    <description>
        smallsteps-child 儿童端业务模块
    </description>

    <dependencies>
        <!-- 通用模块 -->
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-log</artifactId>
        </dependency>
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-parent</artifactId>
        </dependency>
    </dependencies>

</project>
