# ============================================================
# 开发环境配置
# ============================================================

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaozhi?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: xiaozhi
    password: 123456

  # Neo4j 配置
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

# 本地环境邮箱配置
email:
  smtp:
    username: xxx
    password: xxx

dashscope:
  api:
    key: xxx