<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.kenzhao.smallsteps</groupId>
        <artifactId>smallsteps-modules</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>smallsteps-system</artifactId>

    <description>
        system系统模块
    </description>

    <dependencies>
        <!-- 通用工具-->
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-mybatis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-translation</artifactId>
        </dependency>

        <!-- OSS功能模块 -->
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-oss</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-log</artifactId>
        </dependency>

        <!-- excel-->
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-excel</artifactId>
        </dependency>

        <!-- SMS功能模块 -->
        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-tenant</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-security</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-idempotent</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-sensitive</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-encrypt</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-websocket</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-sse</artifactId>
        </dependency>

        <dependency>
            <groupId>com.kenzhao.smallsteps</groupId>
            <artifactId>smallsteps-common-ai</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.github.therapi</groupId>
                            <artifactId>therapi-runtime-javadoc-scribe</artifactId>
                            <version>${therapi-javadoc.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>io.github.linpeilie</groupId>
                            <artifactId>mapstruct-plus-processor</artifactId>
                            <version>${mapstruct-plus.version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${mapstruct-plus.lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${spring-boot.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-parameters</arg>
                        <arg>-J-Dfile.encoding=UTF-8</arg>
                        <arg>-Amapstruct.unmappedTargetPolicy=IGNORE</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
